# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  check-keyword:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check commit message
        run: |
          if [[ ${{ github.event.commits.*.message }} == *"prop"* ]]; then
            echo "Keyword found in commit message. Triggering workflow..."
            keyword_found=true
          else
            echo "Keyword not found in commit message. Skipping workflow..."
            keyword_found=false
          fi
  deploy:
    runs-on: ubuntu-latest
    if: steps.check-keyword.outputs.keyword_found == 'false'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
